name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master

obs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub (INSECURE)
        run: |
          docker login -u "G80M4" -p "dckr_pat_J4jvuzHczI_5hJYfRtsAlWBHK1E"

      - name: Build and push
        run: |
          docker build -t G80M4/java-demo:${{ github.run_number }} .
          docker push G80M4/java-demo:${{ github.run_number }}
